name: Bonjour by a docker
on:
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v3
      - run: cat readme.md | cowsay