name: Bonjour by a docker uses efficiently cowsay
on:
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: Bonjour