name: Read readme by a library with an output variable
on:
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: juliangruber/read-file-action@v1
        id: readme
        with:
          path: ./readme.md
      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: "${{ steps.readme.outputs.content }}"