name: Workflow test de l'application menu server
on:
  - push
jobs:
  workflow_menu-server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.6'
      - run: mvn compile